version: "3"
networks:
   dbnet2:
services:
   mysql: 
     image: mysql:latest
     container_name: mysql
     environment:
        MYSQL_USER: sa
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: test
     networks:
          - dbnet2   
     ports:
           - "3306:3306"   
   phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      networks:
          - dbnet2
      links:
      - "mysql:database"
      ports:
           - "8085:80"     
      environment:
         PMA_HOST: mysql
         PMA_PORT: 3306   

   app-demo:
     build:
       context: .
       dockerfile: Dockerfile
     image: demo-image
     container_name: app-demo
     networks:
          - dbnet2
     links:
      - "mysql:database"
     ports:
         - "8080:8080"
          
  
  